name: Build
# Run this workflow every time a new commit pushed to your repository
on: [pull_request]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    # Name the Job
    name: build
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.6
      - name: test
        run: make test
      - name: build
        run: GOBUILD="linux-amd64 linux-arm64 darwin-amd64 darwin-arm64" make -j build
      - name: artifacts Linux amd64
        uses: actions/upload-artifact@v4
        with:
          name: resec-linux-amd64
          path: build/resec-linux-amd64
      - name: artifacts Linux arm64
        uses: actions/upload-artifact@v4
        with:
          name: resec-linux-arm64
          path: build/resec-linux-arm64
      - name: artifacts MacOS amd64
        uses: actions/upload-artifact@v4
        with:
          name: resec-darwin-amd64
          path: build/resec-darwin-amd64
      - name: artifacts MacOS arm64
        uses: actions/upload-artifact@v4
        with:
          name: resec-darwin-arm64
          path: build/resec-darwin-arm64
